//! Window icon for X11 and Windows (Wayland and macOS take it from the
//! desktop file / bundle).

use winit::window::Icon;

/// 64x64 RGBA, generated by `cargo xtask icons`.
pub fn window_icon() -> Option<Icon> {
    const RGBA: &[u8] = include_bytes!("../assets/icons/generated/window-icon-64.rgba");
    if RGBA.len() != 64 * 64 * 4 {
        return None;
    }
    // A fully transparent file means the icons have not been generated yet.
    if RGBA.as_chunks::<4>().0.iter().all(|p| p[3] == 0) {
        return None;
    }
    Icon::from_rgba(RGBA.to_vec(), 64, 64).ok()
}
